name: First Workflow
on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Step 1 Complete"
          
      - name: Step 2
        run: echo "Step 2 Complete"

job2:
  runs-on: ubuntu-latest

  steps:
    - name: Cowsays
      # You may pin to the exact commit or the version.
      # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
      uses: mscoutermarsh/cowsays-action@v1
      with:
        # What does the cow say?
        text: Ready for Prod - Ship it!!!!!
        # Color of your cow
        color: magenta
          


            
